# Example application which runs the API and a postgres database.
services:
  api:
    build: .
    ports:
      - 9000:9000
    environment:
      TERM: xterm-color
      NODE_ENV: production
      POSTGRES_HOST: database
      POSTGRES_PORT: 5432
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: api
      POSTGRES_SSL_MODE: true
  database:
    image: timescale/timescaledb-ha:pg16
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: api
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db: